In [34]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')
# Show all columns
pd.set_option("display.max_columns", None)

In [35]:
churn = pd.read_csv('D:\Customer-Churn-Analytics\Data\customer_rfm.csv')
churn.head(3)

,customer_id,customer_name,recency,frequency,monetary,r_score,f_score,m_score,rfm_score,customer_segment,churn
0,AA-10315,Alex Avila,185,5,5563.560,2,2,5,9,Potential Loyalists,1
1,AA-10375,Allen Armold,20,9,1056.390,5,5,2,12,Loyal Customers,0
2,AA-10480,Andrew Allen,260,4,1790.512,1,1,3,5,At Risk,1

In [36]:
orders = pd.read_csv('D:\Customer-Churn-Analytics\Data\Featured_superstore.csv')
orders.head(3)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,cost,profit_margin,shipping_days,order_year,order_month,order_quarter,order_days
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136,220.0464,16.0,3,2016,11,4,8
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820,512.3580,30.0,3,2016,11,4,8
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714,7.7486,47.0,4,2016,6,2,12

In [37]:
orders.shape

(9994, 28)

In [38]:
churn.shape

(793, 11)

In [39]:
churn_orders = orders.merge(churn, on='customer_id', how='left')
churn_orders = churn_orders.drop(columns='customer_name_y')

In [40]:
churn_orders.rename(columns={'customer_name_x': 'customer_name'}, inplace=True)

In [41]:
print(orders.shape)
print(churn.shape)
print(churn_orders.shape)

print(churn_orders["churn"].isnull().sum())

print(orders["customer_id"].nunique())
print(churn["customer_id"].nunique())

(9994, 28)
(793, 11)
(9994, 37)
0
793
793

In [44]:
orders[orders["order_id"] == "CA-2016-152156"][
    ['row_id',"order_id", "product_name", "sales"]
]

,row_id,order_id,product_name,sales
0,1,CA-2016-152156,Bush Somerset Collection Bookcase,261.96
1,2,CA-2016-152156,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

In [46]:
churn_orders.to_csv('D:\Customer-Churn-Analytics\Data\FinalChurn_PBI.csv', index=False)